### ISSUE TITLE
[Feature Request] Recommended overplot colours for colormaps

### ISSUE THREAD

**Issue by jacobseiler** [1313e/e13Tools#5]
I'm using the `rainforest` colormap to make a heatmap.  I have some observational data that I wish to plot on top of the heatmap.  A feature that I think would be useful is some suggested colours that pair well with the colormap.  I'm sure it's possible to fiddle around with it myself and get colours that look nice, but I'm sure you have much stronger feelings about this ;)

I've attached an example of my heatmap and the overplotting.  The pink was me having to change a previous light-green that clashed with the colormap.
![const_UV_EW](https://user-images.githubusercontent.com/17869663/64137686-1c061b80-ce3d-11e9-8c63-f2e631d1d1fb.png)

**Comment by 1313e** [comment]
@jacobseiler That is not a bad idea, but I am trying to figure out where exactly I should write that down.
Only thing I can think of is in the online documentation, where the different colormaps are described.

I will have a look.

**Comment by 1313e** [comment]
Generally speaking however, you want to avoid using any green and most blue colors (light blue is fine, but probably hard to see on its own).
I mostly use grey when I am overplotting the `rainforest` colormap.

**Comment by 1313e** [comment]
As all colormaps can now be found in *CMasher*, this is no longer a valid issue.
