### ISSUE TITLE
contribute rainforest to palettable?

### ISSUE THREAD

**Issue by dcherian** [1313e/e13Tools#6]
I was thinking that it would be nice to have `rainforest` in `palettable` (https://jiffyclub.github.io/palettable/, https://github.com/jiffyclub/palettable/)

**Comment by 1313e** [comment]
Hmm, given that matplotlib is not doing anything with my request at this point, that might not be a bad idea.

**Comment by 1313e** [comment]
I have decided now to use my own separate package for my colormaps.
